server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8002
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** # 断言,路径相匹配的进行路由
            - After=2020-06-24T09:59:56.946+08:00[Asia/Shanghai]  # 在这个时间之后的访问才能进入
#            - Cookie=username,Tom # 带有 username = Tom 的cookie允许访问
#            - Header=X-Request-Id, \d+  # 请求头带有 X-Request-Id 允许访问


eureka:
  client:
    # false表示不向自己注册自己
    register-with-eureka: true
    # false表示自己端就是注册中心，我的职责就是要维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server交互的地址，查询服务和注册服务依赖这个地址
      defaultZone: http://localhost:7001/eureka/    # 单机配置
  #      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true # 访问路径显示 IP地址