server:
  port: 81

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # false表示不向自己注册自己
    register-with-eureka: false
    service-url:
      # 设置与 Eureka Server交互的地址，查询服务和注册服务依赖这个地址
      # defaultZone: http://localhost:7001/eureka/    # 单机配置
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/


# 设置feign客户端超时时间（OpenFeign默认支持 ribbon）
ribbon:
  # 指的建立连接后从服务读取到可用资源所用的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间，适用于网络状况下，两端连接所用时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.tom.springcloud.service.PaymentFeignServcie: debug